version: '3'

services:
  web:
    build:
      context: .
    ports:
      - "3000:3000"
    environment:
      - DB_MYSQL_HOST=db
      - DB_MYSQL_PORT=3306
      - DB_MYSQL_USER=flask
      - DB_MYSQL_PASSWORD=flask
      - DB_MYSQL_NAME=flask
    volumes:
      - ./logs:/web/logs
    depends_on:
      - db

  proxy:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./.htpasswd:/etc/nginx/.htpasswd:ro
    ports:
      - "8080:80"
    depends_on:
      - web

  db:
    image: 'jc21/mariadb-aria:latest'
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=flask
      - MYSQL_DATABASE=flask
      - MYSQL_USER=flask
      - MYSQL_PASSWORD=flask
    volumes:
      - ./mysql:/var/lib/mysql

networks:
  default:
    name: my-network