version: '3'

services:
  web:
    build:
      context: .
    ports:
      - "3000:3000"

  proxy:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8080:80"
    depends_on:
      - web
